# language: node_js
# node_js:
#   - "6.9"

# branches:
#   only:
#     - master

# cache:
#   directories:
#     - node_modules

# before_script:  
#   - npm install -g @angular/cli

# script:
#   -  npm run build.ci

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master

# notifications:
#   email:
#     on_failure: change
#     on_success: change